import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "@providers";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import './globals.css'
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Posty",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <UserProvider>
      <body className={inter.className}>
      <NextTopLoader color='#1f75ff' showSpinner={false}
      />
      <Providers>
        {children}
      </Providers>
      </body>
    </UserProvider>
    </html>
  );
}
